// Generated by gencpp from file buff_pkg/State.msg
// DO NOT EDIT!


#ifndef BUFF_PKG_MESSAGE_STATE_H
#define BUFF_PKG_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace buff_pkg
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : number(0)  {
    }
  State_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::buff_pkg::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::buff_pkg::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::buff_pkg::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::buff_pkg::State > StatePtr;
typedef boost::shared_ptr< ::buff_pkg::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::buff_pkg::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::buff_pkg::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::buff_pkg::State_<ContainerAllocator1> & lhs, const ::buff_pkg::State_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::buff_pkg::State_<ContainerAllocator1> & lhs, const ::buff_pkg::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace buff_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::buff_pkg::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::buff_pkg::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::buff_pkg::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::buff_pkg::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::buff_pkg::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::buff_pkg::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::buff_pkg::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2474488a3908093ec1307bdd5b35815e";
  }

  static const char* value(const ::buff_pkg::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2474488a3908093eULL;
  static const uint64_t static_value2 = 0xc1307bdd5b35815eULL;
};

template<class ContainerAllocator>
struct DataType< ::buff_pkg::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "buff_pkg/State";
  }

  static const char* value(const ::buff_pkg::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::buff_pkg::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 number\n"
;
  }

  static const char* value(const ::buff_pkg::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::buff_pkg::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::buff_pkg::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::buff_pkg::State_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUFF_PKG_MESSAGE_STATE_H
